# Generated by Django 4.2.30 on 2026-06-30 04:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_donation_branch_fundallocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiary",
            options={"ordering": ["name"], "verbose_name_plural": "Beneficiaries"},
        ),
        migrations.RenameField(
            model_name="beneficiary",
            old_name="date",
            new_name="registered_date",
        ),
        migrations.RemoveField(
            model_name="beneficiary",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="beneficiary",
            name="count",
        ),
        migrations.RemoveField(
            model_name="beneficiary",
            name="meal_type",
        ),
        migrations.RemoveField(
            model_name="beneficiary",
            name="notes",
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="registered_branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_beneficiaries",
                to="core.branch",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AidDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "aid_type",
                    models.CharField(
                        choices=[
                            ("meal", "Meal"),
                            ("medicine", "Medicine"),
                            ("clothing", "Clothing"),
                            ("other", "Other"),
                        ],
                        default="meal",
                        max_length=20,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="core.beneficiary",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
