# Generated by Django 4.2.30 on 2026-06-30 05:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_project_expense_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("date_assigned", models.DateField(default=django.utils.timezone.now)),
                (
                    "hours_spent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of volunteer hours contributed",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.project",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.volunteer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_assigned", "-id"],
            },
        ),
    ]
