# Generated by Django 4.2.30 on 2026-06-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_volunteerassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiddistribution",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aid_distributions",
                to="core.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="aiddistribution",
            name="inventory_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aid_distribution",
                to="core.inventorytransaction",
            ),
        ),
    ]
