# Generated by Django 4.2.30 on 2026-06-30 08:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_aiddistribution_inventory_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                choices=[("cash", "Cash"), ("item", "Item / In-kind")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="inventory_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_donation",
                to="core.inventorytransaction",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="item_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("food", "Food"),
                    ("medicine", "Medicine"),
                    ("clothing", "Clothing"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="item_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="item_unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="target_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_donations",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_signups",
                to="core.donor",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_mode",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("online", "Online"), ("cheque", "Cheque")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("branch_head", "Branch Head"),
                            ("donor", "Donor"),
                        ],
                        default="donor",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_heads",
                        to="core.branch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
